spring:
  #Database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mar?characterEncoding=utf-8&userSSL=false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml