spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: share
    password: Sqlpassword#
    url: jdbc:mysql://sh-cynosdbmysql-grp-bfycoc5a.sql.tencentcdb.com:25809/marked?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl