spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ab$123456789
    url: jdbc:mysql://sh-cynosdbmysql-grp-203oxgtu.sql.tencentcdb.com:24885/mar


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl