spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sqlpassword
    url: jdbc:mysql://1.12.222.228:3306/marked?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl